apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-qmgr02
- target:
    kind: RoleBinding
    name: overwrite
  patch: |-
    - op: replace
      path: /metadata/name
      value: admin-app-qmgr02
    - op: replace
      path: /metadata/namespace
      value: app-qmgr02
- target:
    kind: AppProject
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-qmgr02
    - op: replace
      path: /spec/description
      value: QMgr 02 Project
    - op: replace
      path: /spec/destinations/0/namespace
      value: app-qmgr02
