apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-bamoe-services
- target:
    kind: AppProject
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-bamoe-services
    - op: replace
      path: /spec/description
      value: BAMOE Services and Application
    - op: replace
      path: /spec/destinations/0/namespace
      value: app-bamoe-services
    - op: add
      path: /spec/destinations/1/namespace
      value: keycloak
