resources:
- ./clusterset-placement.yaml
- ../../../tenants/project-spaces/mq-qmgr01
- ../../../tenants/project-spaces/mq-qmgr02
- ../../../tenants/project-spaces/apic

components:
- https://github.com/ldesrosi/gitops-components-library/components/operators/cert-manager/acm
- https://github.com/ldesrosi/gitops-components-library/components/operators/ibm-mq/acm
- https://github.com/ldesrosi/gitops-components-library/components/operators/ibm-ace/acm
