resources:
- ./clusterset-placement.yaml
- ../../../tenants/project-spaces/mq-qmgr01
- ../../../tenants/project-spaces/mq-qmgr02

components:
- https://github.com/andrewdavies-net/gitops-components-library/components/operators/gitops/acm
- https://github.com/andrewdavies-net/gitops-components-library/components/operators/cert-manager/acm
- https://github.com/andrewdavies-net/gitops-components-library/components/operators/ibm-mq/acm
- https://github.com/andrewdavies-net/gitops-components-library/components/operators/ibm-ace/acm
- https://github.com/andrewdavies-net/mq-test-instance/environments/dev/qmgr01/acm