apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Namespace
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-apic
- target:
    kind: AppProject
    name: default-name
  patch: |-
    - op: replace
      path: /metadata/name
      value: app-apic
    - op: replace
      path: /spec/description
      value: API Connect Namespace
    - op: replace
      path: /spec/destinations/0/namespace
      value: app-apic
